### ISSUE TITLE
Studienleuchte

### ISSUE THREAD

**Issue by thiilo** [PDA-UR/VR4Ware#10]
### Plan
Die Studienleuchte, eine Statuslampe über dem VR4-Studio, sollte basierend auf Raumbuchungen oder lokalem Auslöser aktiviert und deaktiviert werden.
_Ausführlichere Doku (noch) in "Formlose Notizen"_

### To-Do
- [x] Switch on/off auslesen
- [x] separate LED zum laufen bringen
- [x] MQTT zu ioBrocker schicken (einmal pro click)
- [x] separate Skripte zusammenfügen und zum laufen bringen
  - [x] "Eingebaute" LED zum laufen bringen 
- [ ] Stromsparoption einbauen
- [x] Installation im Case
- [x] Test, ob LED für Sichtbarkeit ausreicht 
- [x] Installation an der Wand (am 10.09.24)
- [x] #4 

### Probleme
- Im Switch eingebaute Glimmlampe funktioniert nicht.
  - vermultich vom d1 mini aus nicht power-bar
  - Lampe  brauch 230 Volt
  - an Steckdose hängen
- Arduino IDE zickt manchmal (zeigt keine Ausgaben mehr an) -> Program schließen hilft
- Arduino IDE kann manchmal nicht den _packet header_ finden (vmtl wegen 8x8 Matrix) -> während upload die D1/2/... pins (von 8x8 Matrix) ausstecken und wenn der Code geschrieben wird wieder einstecken
- Im Switch eingebaute Lampe ist zu umständlich zum Laufen zu bringen, deswegen wurde sie für eine normale LED ausgetauscht
- Stromsparoption vermutlich mittles Light Sleep, das wartet auf GPIO interrupt (also braucht zusätzlichen Pin)
